[package]
name = "minesweeper-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
cli-table = "0.4.7"
colored = "2.0.4"
rand = "0.8.5"
